---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    ruby_version: 2.1.2
    homebrew_packages_packages:
      - { name: rbenv }
      - { name: ruby-build }

  pre_tasks:
    - command: brew -v
      ignore_errors: true
      register: brew_exist
    - name: 'homebrew: install'
      shell: 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" '
      when: brew_exist|failed

  roles:
    - hnakamur.homebrew-packages

  tasks:
    - name: check whether a specific version of ruby is installed or not
      shell: rbenv versions | grep {{ ruby_version }}
      register: ruby_installed
      ignore_errors: yes
    - name: install ruby with rbenv
      command: rbenv install {{ ruby_version }}
      when: ruby_installed|failed
    - name: set ruby version global
      command: rbenv global {{ruby_version}}
      when: ruby_installed|failed
    - name: write rbenv path
      shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
      when: ruby_installed|failed
    - name: reload .bash_profile
      shell: source ~/.bash_profile
      when: ruby_installed|failed
    - name: install bundler gem
      command: gem install bundler --no-ri --no-rdoc
    - name: rbenv rehash
      command: rbenv rehash
